name: example-environment
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - matplotlib=3.4.2
  - numpy=1.21.2
  - pip
  - pip:
    - geos
    - pyproj==3.0.1
    - pyshp==2.1.3
    - 'https://github.com/matplotlib/basemap/archive/master.zip'