name: example-environment
channels:
  - conda-forge
dependencies:
  - python=3.7.6
  - pip
  - pip:
    - matplotlib==3.4.2
    - numpy==1.21.2
    - geos
    - geopandas==0.8.2
    - pandas==1.3.1
    - fiona==1.8.18
    - shapely==1.7.1
    - rtree==0.9.7
    - geopy==1.22.0
    - pyproj==3.0.1
    - networkx==2.3
    - seaborn==0.11.2
    - plotly==4.14.3
    - pyshp==2.1.3 
  - basemap
  - basemap-data-hires
  - geos=3.6.2
  - proj=7.2.1
  - gdal=2.4.4
    